### PR TITLE
initial version

### PR DESCRIPTION
**Pull request by fhrbata**
Initial version of the esp-idf-sbom-action, which allows to check for vulnerabilities based on information in manifest files presented in repository and send a short status message to a mattermost channel.

### CODE REVIEW

**Review by dobairoland — APPROVED** [review]
Thanks @fhrbata. LGTM. My optional suggestion is to prefix the secrets with something clearly indicating the name of the tool is using it/them. This might be helpful when this action is added to a larger project with other secrets.

Do we want to have JIRA integration for this or users should be submit issues elsewhere? My assumption was the first one - therefore some template workflow files were auto-generated. Could you please set JIRA_COMPONENT `tools` or `sbom_tool` for them, or (if the you prefer the second option) completely remove them? This can be done in a separate PR as well (based on your preferences).

**Comment by fhrbata** [comment]
> Thanks @fhrbata. LGTM. My optional suggestion is to prefix the secrets with something clearly indicating the name of the tool is using it/them. This might be helpful when this action is added to a larger project with other secrets.

This is good point. Would `SBOM_MATTERMOST_WEBHOOK` work or should we use something even more specific like `ESP_IDF_SBOM_ACTION_MATTERMOST_WEBHOOK`

> 
> Do we want to have JIRA integration for this or users should be submit issues elsewhere? My assumption was the first one - therefore some template workflow files were auto-generated. Could you please set JIRA_COMPONENT `tools` or `sbom_tool` for them, or (if the you prefer the second option) completely remove them? This can be done in a separate PR as well (based on your preferences).

I think using `sbom_tool` jira component makes sense. I will change it, but I will probably need your help with setting the secrets `JIRA_(PASS|URL|USER)`. Thank you for suggesting this.

**Comment by dobairoland** [comment]
Both of those variables LGTM.

Don't worry about JIRA secrets. They are already available through the espressif group.

**Comment by fhrbata** [comment]
@dobairoland I added the suggested changes, but please let me know if you prefer e.g. different name for the secret for mattermost. I also changed `JIRA_PROJECT` to `IDFGH`, so hopefully is should be set the same way as `esp-idf-sbom`. I think it make sense to keep this under `sbom_tool` in jira. Also I will kindly ask you if you can help with the other jira secrets which should be probably set in this repo. Thank you

**Comment by fhrbata** [comment]
> Both of those variables LGTM.
> 
> Don't worry about JIRA secrets. They are already available through the espressif group.

Ah, I can see it now `Organization secrets`. I should have scrolled to the bottom of the page. In that case I believe we should be all set, unless I've missed something. Thank you

**Comment by dobairoland** [comment]
Everything LGTM. Thank you!

**Comment by fhrbata** [comment]
@dobairoland , thank you very much for the review and suggestion. I'm going to merge this.

**Pull request merged**
